"""
Django settings for cemp project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
from cryptography.fernet import Fernet  


BASE_DIR = Path(__file__).resolve().parent.parent




















LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "logs/debug.log"),
            "formatter": "verbose",  
        },
    },
    "loggers": {
        "django": {
            "handlers": ["file"],
            "level": "INFO",
            "propagate": True,
        },
    },
}




LOGIN_URL = "/register/login/"





SECRET_KEY = "<CHANGE_ME_DJANGO_SECRET_KEY>"




FERNET_KEY_FILE_PATH = os.path.join(BASE_DIR, "static", "Fernet_key", "FernetKey")

with open(FERNET_KEY_FILE_PATH, "rb") as key_file:
    FERNET_SECRET_KEY = (
        key_file.read().strip()
    )  



DEBUG = True


ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "<PRIVATE_IP>",
    "0.0.0.0",
    "<PRIVATE_IP>",
    "example.com",
    "<PRIVATE_IP>",
    "<PRIVATE_IP>",
    "<PRIVATE_IP>",
    "example.com",
]


CSRF_TRUSTED_ORIGINS = [
    "https://example.com",
    "https://example.com",
    "http://<PRIVATE_IP>:4173",
    "http://<PRIVATE_IP>:4174",
    "http://<PRIVATE_IP>:8686",
    "http://<PRIVATE_IP>:4173",
    "http://<PRIVATE_IP>:4174",
    
]
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3001",
    "http://<PRIVATE_IP>:4173",
    "http://<PRIVATE_IP>:4174",
    "http://<PRIVATE_IP>:4174",
    "http://<PRIVATE_IP>:3001",
    "http://<PRIVATE_IP>:4173",
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    "content-type",
    "x-csrftoken",
    "authorization",
    "x-requested-with",
]


SESSION_COOKIE_SAMESITE = "Lax"  
SESSION_COOKIE_SECURE = False  
SESSION_COOKIE_PATH = "/"  
SESSION_COOKIE_HTTPONLY = True  
CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]



INSTALLED_APPS = [
    "ionic_liquid.apps.IonicLiquidConfig",
    "polymer.apps.PolymerConfig",
    "crystals.apps.CrystalsConfig",
    "battery_manage_system.apps.BatteryManageSystemConfig",
    "register.apps.RegisterConfig",
    "home.apps.HomeConfig",
    "tickets.apps.TicketsConfig",
    "autocompute.apps.AutocomputeConfig",
    "contributor",
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_cron",  
    "rest_framework",  
    "rest_framework.authtoken",  
    "django.contrib.sitemaps",  
    
]



REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",  
        "rest_framework.authentication.TokenAuthentication",  
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",  
    ],
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",  
    "django.middleware.common.CommonMiddleware",  
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    
]

X_FRAME_OPTIONS = "SAMEORIGIN"

ROOT_URLCONF = "cemp.urls"





TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                
            ],
        },
    },
]

WSGI_APPLICATION = "cemp.wsgi.application"





DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "public_example.sqlite3",
        "OPTIONS": {
            "timeout": 30,
        },
    },
    "mysql": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "mydb",
        "USER": "root",
        "PASSWORD": "<CHANGE_ME_DB_PASSWORD>",
        "HOST": "127.0.0.1",
        "PORT": 3306,
    },
}


DATABASE_ROUTERS = ["crystals.routers.MyRouter"]




AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]





LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Shanghai"


USE_I18N = True

USE_TZ = True




STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(
    BASE_DIR, "staticfiles"
)  

STATICFILES_DIRS = [
    BASE_DIR / "autocompute/static",
    BASE_DIR / "home/static",
    BASE_DIR / "ionic_liquid/static",
    BASE_DIR / "contributor/static",
    BASE_DIR / "polymer/static",
    BASE_DIR / "crystals/static",
    BASE_DIR / "static",
]





DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")






MARKOV_GDYNET_PACKAGE_DIR = os.environ.get(
    "CEMP_MARKOV_GDYNET_PACKAGE_DIR",
    "/path/to/example/46_markov_chain/gdynet-pytorch",
)
CEMP_AGENT_MARKOV_CONTROLLER_URL = os.environ.get(
    "CEMP_AGENT_MARKOV_CONTROLLER_URL",
    "http://11.tcp.vip.cpolar.cn:13840/api/internal/markov/jobs",
)
MARKOV_AGENT_POLL_INTERVAL_SECONDS = int(os.environ.get("CEMP_MARKOV_AGENT_POLL_INTERVAL_SECONDS", "20"))
MARKOV_AGENT_TIMEOUT_SECONDS = int(os.environ.get("CEMP_MARKOV_AGENT_TIMEOUT_SECONDS", str(7 * 24 * 60 * 60)))


CRON_CLASSES = [
    
    
    
    
    
    
]



EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"  

EMAIL_HOST = "smtp.gmail.com"  
EMAIL_PORT = 587  
EMAIL_USE_TLS = True  
EMAIL_HOST_USER = "user@example.com"  
EMAIL_HOST_PASSWORD = "<CHANGE_ME_PASSWORD>"  
DEFAULT_FROM_EMAIL = "CEMP Platform <user@example.com>"  
EMAIL_TIMEOUT = 10  
TICKETS_EMAIL_ASYNC = True  
TICKETS_ENABLE_EMAIL_NOTIFICATIONS = False  



SITE_DOMAIN = "https://example.com"  

