name: cemp-public
channels:
  - pytorch
  - pyg
  - conda-forge
dependencies:
  - python=3.11
  - django=4.2.3
  - djangorestframework
  - django-cors-headers
  - cryptography
  - pandas=1.5.3
  - openpyxl
  - numpy
  - scikit-learn
  - xgboost=1.7.6
  - beautifulsoup4
  - cairosvg=2.7.0
  - ipython
  - matplotlib
  - more-itertools
  - openbabel
  - rdkit=2023.03.2
  - seaborn
  - pytorch=2.4.*
  - cpuonly
  - pyg=2.6.1=py311_torch_2.4.0_cpu
  - pip
  - pip:
      - django-cron
      - mp-api
